server:
  port: 8081

spring:
  application:
    name: vehicle-service
  kafka:
    bootstrap-servers: localhost:8097
    producer:
      retries: 3
      acks: all
app:
  vehicle-coordinates-topic:
    name: vehicle-coordinates-topic
    partition: 3
    replication: 2

logging:
  level:
    org.springframework.transaction: trace
    org.springframework.kafka.transaction: debug

