server:
  port: 8082

spring:
  application:
    name: tracker-service
  kafka:
    bootstrap-servers: localhost:8097
    producer:
      retries: 3
      acks: all
    consumer:
      auto-offset-reset: earliest
      group-id: vehicle-coordinates-group-1
      enable-auto-commit: true

app:
  vehicle-coordinates-topic:
    name: vehicle-coordinates-topic
    partition: 3
    replication: 2
  coordinates-logging-topic:
    name: coordinates-logging-topic
    partition: 3
    replication: 2