server:
  port: 8083

spring:
  application:
    name: coordinates-logger-service
  kafka:
    bootstrap-servers: localhost:8097
    consumer:
      auto-offset-reset: earliest
      group-id: coordinates-logging-group-1
      enable-auto-commit: true

app:
  coordinates-logging-topic:
    name: coordinates-logging-topic
